name: Build Pipeline
#This build pipeline does two jobs, it clones the repository as one job in case the repository doesn't exist. Then it builds the flutter app. This is set to run on ubuntu-latest just like the devcontainer
#It runs a default command of working-directory ./basicapp to reduce the number of lines used. Then it proceeds to get flutter dependencies with flutter pub get, runs the flutter app tests with flutter test
#It then builds the flutter web app with flutter build web
#Action is taken from flutter actions (https://github.com/marketplace/actions/flutter-action)
#learned about defaults here (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iddefaultsrunworking-directory)
on:
  push:
    branches: [ "main" ]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://github.com/JosephCGit/JCDevContainer
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./basicapp
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: Run provided Flutter app tests
        run: flutter test
      - name: Build Flutter application
        run: flutter build web
