# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: clone repository
      - run: git clone https://github.com/JosephCGit/JCDevContainer
      - name: Get Flutter dependencies
      - working-directory: ./basicapp
      - run: flutter pub get
      - name: Run provided Flutter app tests
      - working-directory: ./basicapp
      - run: flutter test
      - name: Build Flutter application
      - working-directory: ./basicapp
      - run: flutter build web
